#define BOARD_OSPI0_RXDS_GPIO_PORT  1
#define BOARD_OSPI0_RXDS_GPIO_PIN   6

#define BOARD_OSPI0_D0_GPIO_PORT    2
#define BOARD_OSPI0_D0_GPIO_PIN     0

#define BOARD_OSPI0_D1_GPIO_PORT    2
#define BOARD_OSPI0_D1_GPIO_PIN     1

#define BOARD_OSPI0_D2_GPIO_PORT    2
#define BOARD_OSPI0_D2_GPIO_PIN     2

#define BOARD_OSPI0_D3_GPIO_PORT    2
#define BOARD_OSPI0_D3_GPIO_PIN     3

#define BOARD_OSPI0_D4_GPIO_PORT    2
#define BOARD_OSPI0_D4_GPIO_PIN     4

#define BOARD_OSPI0_D5_GPIO_PORT    2
#define BOARD_OSPI0_D5_GPIO_PIN     5

#define BOARD_OSPI0_D6_GPIO_PORT    2
#define BOARD_OSPI0_D6_GPIO_PIN     6

#define BOARD_OSPI0_D7_GPIO_PORT    2
#define BOARD_OSPI0_D7_GPIO_PIN     7

#define BOARD_OSPI0_SCLK_GPIO_PORT  3
#define BOARD_OSPI0_SCLK_GPIO_PIN   0

#define BOARD_OSPI0_SCLKN_GPIO_PORT 3
#define BOARD_OSPI0_SCLKN_GPIO_PIN  1

#define BOARD_OSPI0_SS0_GPIO_PORT   3
#define BOARD_OSPI0_SS0_GPIO_PIN    2
